"""posts table

Revision ID: 06da98a07a8f
Revises: 
Create Date: 2026-06-07 04:14:25.773059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06da98a07a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.drop_index(batch_op.f('ix_post_post_type'))
        batch_op.drop_index(batch_op.f('ix_post_date_posted'))

    op.drop_table('post')
    # ### end Alembic commands ###
